config/routes.rb
Rails.application.routes.draw do
  

  

  resources :uploders,only: [:show]

  resources :albums do
  	resources :pics , except: [:show,:index]
  end	
  devise_for :users

  root to: "welcome#home"


end

app/models/album.rb
class Album
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :name, type: String
  field :user_id
  
  validates_presence_of :name  #name can't be empty

  belongs_to :user
  has_many :pics,dependent: :destroy #when a user will be deleted its associated pics becomes useless

end

app/models/pic.rb
class Pic
  include Mongoid::Document
  include Mongoid::Timestamps  # for getting created_at time 
  include Mongoid::Paperclip   # paperclip gem lib
  
  field :title, type: String
  field :album_id
  field :user_id


  has_mongoid_attached_file :avatar,
  :styles => {
      :thumb => "200x200#",
      :small  => "20x20>",
      :medium => "350x350#{}" }
  
validates_attachment_file_name :avatar, :matches => [/png\Z/, /jpe?g\Z/, /gif\Z/]  #regex for image content type
validates_presence_of :title
validate :pic_limit, :on => :create #Limiting the Pics limit to be created less than 25

  belongs_to :user
  belongs_to :album


  def pic_limit
    if self.user.pics(:reload).count > 25
      errors.add(:base, "Your not Allowed to add more than 25 pics")
    end
  end

end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  has_many :albums,dependent: :destroy
  has_many :pics,dependent: :destroy

  
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :authenticate_user!, except: [:index,:show]
  before_action :set_album, only: [:show, :edit, :update, :destroy]


  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
   @pics = Pic.where(album: @album.id)
  end

  # GET /albums/new
  def new
    @album =current_user.albums.build

  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = current_user.albums.build(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:user_id, :name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
  before_action :set_pic, only: [ :edit, :update, :destroy]
  before_action :set_album
 

  # GET /pics/new
  def new
    @pic = Pic.new
  end

  # GET /pics/1/edit
  # def edit
  # end

  # POST /pics
  # POST /pics.json
  def create
    @pic = Pic.new(pic_params)
    @pic.user_id = current_user.id
    @pic.album_id = @album.id


    respond_to do |format|
      if @pic.save
        format.html { redirect_to @album, notice: 'Pic was successfully created.' }
        format.json { render :show, status: :created, location: @pic }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pics/1
  # PATCH/PUT /pics/1.json
  # def update
  #   respond_to do |format|
  #     if @pic.update(pic_params)
  #       format.html { redirect_to @album, notice: 'Pic was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @pic }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @pic.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /pics/1
  # DELETE /pics/1.json
  def destroy
    @pic.destroy
    respond_to do |format|
      format.html { redirect_to @album, notice: 'Pic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pic
      @pic = Pic.find(params[:id])
    end

    def set_album
      @album = Album.find(params[:album_id])
      
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pic_params
      params.require(:pic).permit(:user_id, :album_id, :title,:avatar)
    end
end

app/controllers/uploders_controller.rb
class UplodersController < ApplicationController
  
  def show
  	@user = User.find(params[:id])
  	@user_albums = @user.albums
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def home
  	@pics = Pic.all.desc('_id').limit(25).to_a
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name,class: "form-control" %>
  </div><br>
  <div class="box-footer">
    <%= f.submit class: "btn btn-danger"%>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing Album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<p id="notice"><%= notice %></p>

<h1 style="text-align: center">All Albums</h1>
<% if user_signed_in? %>
  <%= link_to "Add Album",new_album_path ,class: "btn  btn-lg btn-primary",style: "margin-bottom: 40px"%>
<% end %>


  
<% @albums.each do |album| %>
  <div class="container" style="width:100%;">
      <div class="row">
        <div class="col-md-4" style="text-align: center;border: 1px solid #ccc">
            <div style = "padding:5px;">
              <div class="panel panel-info">
                <div class="panel-heading"><h3><%= link_to album.name,album_path(album) %></h3></div>
                  <div class="panel-body">
                    <b>uploded  <%= time_ago_in_words(album.created_at)%> ago &nbspby&nbsp <strong style ="color:lightblue"><%= link_to album.user.email,uploder_path(album.user) %></strong></b><br>
                    <span class="glyphicon glyphicon-search"></span><%= link_to 'Show', album %>
                    <%  if user_signed_in? && current_user.try(:id) == album.user.id %>
                       <%= link_to 'Edit', edit_album_path(album) %>
                       <%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %>
                    <% end %>
                </div>
              </div> 
            </div></br>
        </div>      
      <% end %>
      </div>
  </div>    
 

app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>
<div style="float:right">
  <% if user_signed_in?  && current_user.try(:id) == @album.user.id %>
   <%= link_to 'Upload a Pic', new_album_pic_path(@album),class: "btn btn-danger"  %> 
  <% end %>
</div>
<%= link_to 'Back', albums_path %>
<h1 style="text-align: center"><%= @album.name %></h1><br>
<% @pics.each do |p| %>
	<div class="container" style="width:100%;">
  		<div class="row">
    		<div class="col-md-4" style="text-align: center;border: 1px solid #ccc">
        	<div style = "padding:5px;">
  				  <%= image_tag p.avatar.url(:thumb)%>
  				  <div style="margin-top: 5px">
              <%= p.title%><br>
              <b>uploded  <%= time_ago_in_words(p.created_at)%> ago &nbspby&nbsp <strong style ="color:lightblue"><%= link_to p.user.email,uploder_path(p.user) %></strong></b><br>
              <%= link_to 'Destroy',[@album,p], method: :delete, data: { confirm: 'Are you sure?' } %>
            </div> 
          </div><br>
 			  </div>		
       <% end %>
  		</div>
	</div>		

    
  
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SampleApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<!-- Navbar -->

	<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Pixel-S",root_path,class: "navbar-brand"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li></li>
        <li><%= link_to "Albums" ,albums_path%></li>
        
      </ul>
     
      <ul class="nav navbar-nav navbar-right">
      	<% if current_user %>
          <li><%= link_to "Log_out", destroy_user_session_path,method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign_in", new_user_session_path%></li>/<li><%= link_to "Sign_up", new_user_registration_path%></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class="jumbotron" style="background-image: linear-gradient(-225deg, #AC32E4 0%, #7918F2 48%, #4801FF 100%);">
  <div style="margin-left: 50px">
    <h1>Pixel-S</h1>      
    <p>Speak through Pictures</p>
    <% if !user_signed_in? %>
      <p>Please Sign-up to add Your Own Albums and Pictures </p><span><%= link_to "Sign_up", new_user_registration_path ,class: "btn btn-lg btn-primary"%></span>
    <% end %>  
  </div>  
</div>
<div class="container">
	<%= yield %>
</div>
</body>
</html>

app/views/pics/_form.html.erb
<%= form_for([@album,@pic]) do |f| %>
  <% if @pic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pic.errors.count, "error") %> prohibited this pic from being saved:</h2>

      <ul>
      <% @pic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title ,class: "form-control"%>
  </div>

  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar,class: "form-control" %>
  </div><br>

  <div class="box-footer">
    <%= f.submit class: "btn btn-danger" %>
  </div>
<% end %>

app/views/pics/edit.html.erb
<h1>Editing Pic</h1>

<%= render 'form' %>

 

app/views/pics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pics</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Album</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pics.each do |pic| %>
      <tr>
        <td><%= pic.user %></td>
        <td><%= pic.album %></td>
        <td><%= pic.title %></td>
        <td><%= link_to 'Show', pic %></td>
        <td><%= link_to 'Edit', edit_pic_path(pic) %></td>
        <td><%= link_to 'Destroy', pic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pic', new_pic_path %>

app/views/pics/new.html.erb
<h1>New Pic</h1>

<%= render 'form' %>

app/views/pics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @pic.user %>
</p>

<p>
  <strong>Album:</strong>
  <%= @pic.album %>
</p>

<p>
  <strong>Title:</strong>
  <%= @pic.title %>
</p>

<%= link_to 'Edit', edit_pic_path(@pic) %> |
<%= link_to 'Back', pics_path %>

app/views/uploders/show.html.erb
<h1>Welcome to <%= @user.email %>'s Album</h1>

<% @user_albums.each do |album| %>
  <div class="container" style="width:100%;">
      <div class="row">
        <div class="col-md-4" style="text-align: center;border: 1px solid #ccc">
            <div style = "padding:5px;">
              <div class="panel panel-info">
                <div class="panel-heading"><h3><%= link_to album.name,album_path(album) %></h3></div>
                  <div class="panel-body">
                    <b>uploded  <%= time_ago_in_words(album.created_at)%> ago &nbspby&nbsp <strong style ="color:lightblue"><%= link_to album.user.email,uploder_path(album.user) %></strong></b><br>
                    <span class="glyphicon glyphicon-search"></span><%= link_to 'Show', album %>
                    <%  if user_signed_in? %>
                       <%= link_to 'Edit', edit_album_path(album) %>
                       <%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %>
                    <% end %>
                </div>
              </div> 
            </div></br>
        </div>      
      <% end %>
      </div>
  </div>  

app/views/welcome/home.html.erb
<% @pics.each do |p| %>
	<div class="container" style="width:100%;">
  		<div class="row">
    		<div class="col-md-3" style="text-align: center;border: 1px solid #ccc">
        		<div style = "padding:5px;">
        			<%= image_tag p.avatar.url(:thumb)%>
        			<div style="margin-top: 5px">
 						<%= p.title%><br>
 					 	<b>uploded  <%= time_ago_in_words(p.created_at)%> ago &nbspby&nbsp <strong style ="color:lightblue"><%= link_to p.user.email,uploder_path(p.user) %></strong></b>
 					</div> 	
 					
 			</div><br>
 				</div>		
<%end%>
  		</div>
	</div>		  